all: WGMT AGNT AGNTD AGNMT AGSAW_YX ACC2mE ACCM Sch_Lab402d MEG_BL Sch_Lab402

WGMT:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

AGNT:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

AGNTD:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

AGNMT:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

AGSAW_YX:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

ACC2mE:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

ACCM:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

Sch_Lab402d:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

MEG_BL:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

Sch_Lab402:
	iverilog $@_tb.v -o $@.out && vvp $@.out
	@echo "-----------Make $@ complete-----------"

clean:
	@rm -f *.out *.vcd
	@echo "-----------Clean complete-----------"
